### ISSUE TITLE
url-pattern does treats fullstops in urls different to express.

### ISSUE THREAD

**Issue by thepont** [snd/url-pattern#12]
The URL `/api/v1/user/test.name/` would be captured by the expressjs route `/api/v1/user/:id/` but is not captured by the url-pattern `/api/v1/user/:id/`.

The resulting regex should include the full stop as a valid char. `\/api\/v1\/user\/([a-zA-Z0-9-_ % \.]+)\/`

**Comment by thepont** [comment]
I guess the intention may not be to copy expresses url patterns, in that case feel free to close it, it says nowhere it does, I was just hoping for a module that did this.

Anyhow the regex I suggested breaks the major/minor version example.

**Comment by snd** [comment]
yes, my intention for url-pattern is not to copy the express behaviour exactly.

i understand your requirement.
there was another issue #6 that asked for named segments to stop consuming at full stops.
that requirement and yours mutually exclude each other.

different users want different charsets to be consumed by named segments !

for that reason i made that charset, among other things, configurable to suit each users needs.

this test case configures the url-pattern compiler to exhibit the behaviour you want by adding the full stop to the set of characters consumed by named segments:
https://github.com/snd/url-pattern/blob/2c3f1aed5c4dbde9e5393d57c48e64065e5a49c8/test/url-pattern.coffee#L416

if you want to know more about modifying the compiler: https://github.com/snd/url-pattern#modifying-the-compiler

you can also change the charset for all instances of url-pattern at once:

``` javascript
UrlPattern.Compiler.prototype.segmentValueCharset = 'a-zA-Z0-9-_ %.;
```

hope i could help.

**Comment by thepont** [comment]
That's great really helpful. Thanks.

**Comment by snd** [comment]
glad i could help!

looking at the test again i noticed that it contained an unnecessary line.
see this improved minimal test case: 
https://github.com/snd/url-pattern/blob/413f16176c51c61f78c1d957a15172fa08a7a0f5/test/url-pattern.coffee#L414
