### ISSUE TITLE
Query strings

### ISSUE THREAD

**Issue by spicydonuts** [snd/url-pattern#13]
I'm wondering what your thoughts are on query strings (`/some/path?a=b`).  I'm working on a routing library and most people expect query strings to not affect the route and simply provide extra data.

1. This isn't something url-pattern should be concerned with (I should append optional query string matchers to each route when creating Patterns or I should remove the query before trying to match on it and deal with it later on my own)
2. Or this is something you've been thinking about and have a better idea on.  The only thing I can think of is an extra parameter to match or the Pattern constructor that says query strings should be ignored for matching but still parsed and merged onto the object returned from match (though probably with less priority than a route capture: `new Pattern('/page/:number').match('/page/1?number=2') => {number: 1}`)

**Comment by snd** [comment]
in my opinion url and querystring are two separate entities with different semantics.
querystrings are definitely outside of url-pattern's focus.
there exist other good libraries for dealing with querystrings: https://github.com/hapijs/qs.

i originally extracted url-pattern from a router library i wrote
(https://github.com/snd/passage) as it was useful on its own.

the router became ridiculously simple in the process:
https://github.com/snd/passage/blob/master/src/passage.coffee
(the router integrates with connect middleware and is entirely side effect free)

the router just removes the querystring from the url and passes the rest to url-pattern.
here's the relevant line:
https://github.com/snd/passage/blob/master/src/passage.coffee#L23

i handle querystrings separately by having a simple middleware that sets `req.query`:

```coffeescript
qs = require 'qs'
url = require 'url'

querystringMiddleware = (req, res, next) ->
  if req.query?
    next()
    return

  if req.url.indexOf('?') is -1
    req.query = {}
  else
    parsedUrl = url.parse req.url
    req.query = qs.parse(parsedUrl.query, options)

  next()
```

**Comment by spicydonuts** [comment]
I agree, and thanks for the code.  I'll give your router a look.  The AST-based rewrite sounds neat too.
