### ISSUE TITLE
matching `~`

### ISSUE THREAD

**Issue by caasi** [snd/url-pattern#15]
I know I can change `compiler.segmentValueCharset` to do that. Just wondering why don't you support all the [unreserved characters](https://tools.ietf.org/html/rfc3986#section-2.3) in RFC3986 (without `.`) by default. Is there any special meaning for `~` in some use cases?

**Comment by snd** [comment]
there's no special meaning for `~` and no specific reason why i left it out.
adding `~` to `compiler.segmentValueCharset` makes a lot of sense.
then all the unreserved characters in RFC3986 (without `.`) should be supported - right ?

**Comment by caasi** [comment]
Thanks for the explanation.

I know nothing about RFC3986 until [react-router-component](/STRML/react-router-component) stop working for paths like `/foobar/0~5000`.

I think adding a `~` is good enough for my case. I will read the tests tomorrow and maybe draft a PR later. :D

**Comment by snd** [comment]
this is now published in 0.10.0.
[there are some breaking changes. click to see the changelog entry.](CHANGELOG.md#010)
