### ISSUE TITLE
how to match for an Ip address

### ISSUE THREAD

**Issue by harrydevnull** [snd/url-pattern#22]
how can I check for an IPV4 address? I tried the below and it failed obviously 
```var pattern = new UrlPattern('/ip/^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}↵
  8 (?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$')```

assume the incoming url is ```ip/10.10.10.10```
could you please help in figuring out the correct pattern?

**Comment by sh** [comment]
Assuming the incoming url is ``/ip/10.10.10.10``
````js
var pattern = new UrlPattern(/\/ip\/(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/);
pattern.match('/ip/10.10.10.10'); 
// returns [ '10', '10', '10', '10' ]
````

Assuming the incoming url is ``ip/10.10.10.10``
````js
var pattern = new UrlPattern(/^\ip\/(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/);
pattern.match('ip/10.10.10.10'); 
// returns [ '10', '10', '10', '10' ]
````

Hope this helps!

**Comment by snd** [comment]
hey harry,

the problem with your above code is that you're passing a string containing a regex to `new UrlPattern`.
in its first argument position `new UrlPattern` either accepts a string containg an url-pattern or a regex object (`/.../`) which is not a string string.
an url-pattern is special syntax that is different from a regex, easier for the cases it covers, but less powerful/general.
you can't exactly match IPs with url-pattern so you have to fall back to regexes and pass in a regex object (`/.../`).

here are three solutions to your requirements:

individual IP components returned as array:
https://github.com/snd/url-pattern/blob/661366c435b0a7e6f0b112751f1b41a72178c37e/test/match-fixtures.coffee#L187

using non capturing groups to extract entire IP:
https://github.com/snd/url-pattern/blob/661366c435b0a7e6f0b112751f1b41a72178c37e/test/match-fixtures.coffee#L177

using non capturing groups and naming the capturing group:
https://github.com/snd/url-pattern/blob/661366c435b0a7e6f0b112751f1b41a72178c37e/test/match-fixtures.coffee#L187
**this is probably the one you want !**

happy to help.
