### ISSUE TITLE
`pattern.match` does not match wildcard paths appropriately if missing trailing slash

### ISSUE THREAD

**Issue by niftylettuce** [snd/url-pattern#24]
If we have a route, such as `/snd/url-pattern` and we do not have a trailing forward slash (in other words, if the route is not `/snd/url-pattern/` with the trailing `/`), then it does not match the wildcard path of `/snd/url-pattern/*` as it should.  Here is a code snippet:

```js
var UrlPattern = require('url-pattern');
var pattern = new UrlPattern('/snd/url-pattern/*');
console.log(pattern.match('/snd/url-pattern')); // returns `null`
```

The only possible idea I have right now to fix this is to use this middleware in order to automatically 301 redirect to trailing slashes https://github.com/avinoamr/connect-slashes.

Do you think you can fix this in your package, or is there a more appropriate way for me to do this?

**Comment by snd** [comment]
hey nifty,

the behaviour of your code snippet is intended!  that `match` should return `null`!
your pattern `/snd/url-pattern/*` expresses the following: match EXACTLY the string`/snd/url-pattern/` followed by anything.

there is no special behaviour for wildcards next to trailing slashes. this is on purpose.

you can however make the slash and the wildcard optional by wrapping them in parentheses. this should do what you want:

```js
var UrlPattern = require('url-pattern');
var pattern = new UrlPattern('/snd/url-pattern(/*)');
console.log(pattern.match('/snd/url-pattern')); // returns `{}`
console.log(pattern.match('/snd/url-pattern/')); // returns `{_: ''}`
console.log(pattern.match('/snd/url-pattern/abc')); // returns `{_: 'abc'}`
```

let me know if this solves your issue.

**Comment by sh** [comment]
Hey nifty,

If you do care about SEO your 301 redirect approach is definitely the best. 
Having the same content served by 2 different urls, eg `/foo` and `/foo/`will result in duplicate content.

See this article [Trailing slashes and SEO](https://en.onpage.org/wiki/Trailing_Slashes) for a short explanation on why this is bad.

**Comment by niftylettuce** [comment]
@sh good to know, thank you 👍
