### ISSUE TITLE
Case sensitivity in patterns 

### ISSUE THREAD

**Issue by evansobkowicz** [snd/url-pattern#25]
Hey - cool package! Is there a way to allow urls to be case insensitive when matching? For example, with this pattern:

`new UrlPattern('(http(s)\\://)(www.)mydomain.com/profile/:username(/)')`

It does not match if I put in:

`https://MYDOMAIN.com/PROFILE/myusername`

Is there an existing way to solve this, or would I need to submit a PR?

**Comment by snd** [comment]
lowercasing the string first should work:

```js
var pattern = new UrlPattern('(http(s)\\://)(www.)mydomain.com/profile/:username(/)');
var string = 'https://MYDOMAIN.com/PROFILE/myusername';

var match = pattern.match(string.toLowerCase());
```

let me know if this solves your problem !
