### ISSUE TITLE
Named portions don't handle `.` (period) character

### ISSUE THREAD

**Issue by TooTallNate** [snd/url-pattern#26]
```
> var p = new Pattern('/foo/:bar/private')
> p.match('/foo/bar/private')
{ bar: 'bar' }
> p.match('/foo/bar.com/private')
null
```

**Comment by snd** [comment]
hey nathan,

that's intended default behaviour.

see the readme section on named segments: https://github.com/snd/url-pattern#named-segments

> when matching, a named segment consumes all characters in the regex character set `a-zA-Z0-9-_~ %`. a named segment match stops at `/`, `.`, ... but not at `_`, `-`, ` `, `%`...

you can change the character set to include the `.` period:
```js
> var options = {
  // we just add the period to the default charset
  segmentValueCharset = 'a-zA-Z0-9-_~%.',
};
> var p = new Pattern('/foo/:bar/private', options);
> p.match('/foo/bar/private')
{ bar: 'bar' }
> p.match('/foo/bar.com/private')
{bar: 'bar.com'}
```

https://github.com/snd/url-pattern#customize-the-pattern-syntax

**Comment by TooTallNate** [comment]
Thanks. Sorry for skipping the docs.
