### ISSUE TITLE
No test for stringify() with the parameters not bound

### ISSUE THREAD

**Issue by dyong0** [snd/url-pattern#28]
I thought that stringify() works well with the parameters not bound. And it really does. For example 
```js
var UrlPattern = require('url-pattern');
var pattern = new UrlPattern('/:overflow');

var not_related_params = {
        foo : 'foo',
        bar : 'bar',
        overflow : 'overflow'
};
var result = pattern.stringify(not_related_params);
console.log(result); //return /overflow
```

But there's no test about this situation. Could you add it?

**Comment by snd** [comment]
yeah, stringify ignores key/value-bindings in the argument object if there's no named segment in the pattern that matches the key. i think this is intuitive (what one would expect).

i don't think this behaviour is critical enough to warrant a test.

you're very welcome to add a test in a PR though !

**Comment by dyong0** [comment]
I've just seen your comment now. Thank you for accepting my opinion.
