### ISSUE TITLE
Array Parameter

### ISSUE THREAD

**Issue by knoxcard** [snd/url-pattern#37]
Instead of doing this...

['two-factor-authentication/*', 'two-factor-authentication/'].forEach(function(route) {
    var two_factor_pattern = new UrlPattern(route)
    if(two_factor_pattern.match(req.url)) next()
})

wouldn't it be be nice to do this??

var two_factor_pattern = new UrlPattern(['two-factor-authentication/*', 'two-factor-authentication/'])
   if(two_factor_pattern.match(req.url)) next()

**Comment by snd** [comment]
the following pattern matches both `'two-factor-authentication/*'` and `'two-factor-authentication/'`:
```js
pattern = UrlPattern('two-factor-authentication/(*)')
```

for other cases you could write yourself a helper like this:
```js
function compoundPattern(patterns) {
    return {
        match: function(string) {
             matches = []
             patterns.forEach(function(pattern) {
                 match = pattern.match(string)
                 if(match != null) {
                      matches.push(match)
                 }
              })
              if (matches.length == 0) {
                  return null
              }
              return matches
        }
    }
}
```

and then use it like this:
```js
pattern = compoundPattern(['two-factor-authentication/*', 'two-factor-authentication/'])
pattern.match(someStringYouWouldLikeToMatch)
```

**this usecase is special enough that i don't want to integrate it into the library**
