### ISSUE TITLE
Allow period in params

### ISSUE THREAD

**Issue by MiniGod** [snd/url-pattern#38]
With the following pattern: `/download/:filename`, it would be nice to get the full filename including the file extension.

E.g. `pattern.match('/download/avatar.png')` should return: `{ filename: 'avatar.png' }`.

A workaround for now is to do a pattern like `/download/:filename(.png)`, but then I will not get the file ext in `filename`.

**Comment by snd** [comment]
try if the pattern `/download/:filename(.:extension)` works for you!

alternatively, if the extension should not be optional: `/download/:filename.:extension`

**Comment by MiniGod** [comment]
I see you have strong opinions about your module. That's good! I like it! 

This all came from transitioning from micro-api to microrouter (linked above from that pr) and this issue (and #39) were differences / annoyances that I encountered. I know that's doesn't concern this module at all, so feel free to close this.
