### ISSUE TITLE
Ignore final slash

### ISSUE THREAD

**Issue by MiniGod** [snd/url-pattern#39]
In my opinion, the pattern `/:name` should match both `/bob` and `/bob/`.

Using this workaround for now: `/:name(/)`.

**Comment by snd** [comment]
hey kristjan, different people want different things out of this package.

if i'd follow your suggestion and make the pattern `/:name` match both `/bob` and `/bob/` there would be others that open issues like "how can i make /:name not match if there's a trailing slash" etc. you get the idea.

currently you're able to explicitly state and achieve both. even if it means typing 3 more chars ;)

**Comment by MiniGod** [comment]
snds good to me ;)
