### ISSUE TITLE
cannot parse float number as named param

### ISSUE THREAD

**Issue by zhaoyao91** [snd/url-pattern#40]
I have such a pattern
```
new UrlPattern('/:number')
```
it can match `localhost:3000/1`, `localhost:3000/abc`, but it cannot match `localhost:3000/1.23`

**Comment by snd** [comment]
i'd recommend reading the section on named segments and how to customize them

https://github.com/snd/url-pattern#named-segments

especially this:

when matching, a named segment consumes all characters in the regex character set `a-zA-Z0-9-_~ %`. a named segment match stops at `/`, `.`, ... but not at `_`, `-`, ` `, `%`...

you want it to not stop at `.`.

you can achieve that by adding the `.` to the segment value charset:

```js
var pattern = new UrlPattern('/:number', {
   segmentValueCharset: "a-zA-Z0-9-_~ %."
})
```

**Comment by zhaoyao91** [comment]
thanks, I should have read it.
