### ISSUE TITLE
Require one of a few possible values?

### ISSUE THREAD

**Issue by jkillian** [snd/url-pattern#47]
Is is possible to match something like this, all in one `URLPattern`?

```
a/(b|c|d)/:var
```

In short, the path must contain exactly one of b, c, or d before the variable portion of the path. I read over the docs / test cases and didn't see anything like this, but apologies if I missed it!

**Comment by snd** [comment]
you're right. there's no way to do this. that's intentional, to keep it simple. you can always use regexes.

you could do something like this however:
```javascript
function match(string) {
  var matches = UrlPattern("a/:enum/:var").match(string);
  if (matches == null || !["b", "c", "d"].includes(match.enum) {
    return null;
  }
  return matches;
}
```

**Comment by jkillian** [comment]
Thanks for the quick response @snd! I agree with you that in some cases, a workaround is fairly easy. Things get trickier though when using external libraries that take a single `URLPattern` as an argument.

Up to you whether this is worth supporting, your [predicate idea](https://github.com/snd/url-pattern/issues/18) might work nicely here actually!

**Comment by randomdevpete** [comment]
I tend to think overloading the pattern syntax with too many options and a lot more sugar is not what a library like this needs. In my routing library which uses url-pattern, I just provide a callback after matching where you can apply any extra matching logic you need on the matched terms. You can never account for every possibility a user might want so at a certain point its best to just let them write code and/or allow regexes.

**Comment by snd** [comment]
closing this since i agree with @chucksellick's previous comment
