### ISSUE TITLE
Fails when the pattern has a dot

### ISSUE THREAD

**Issue by hacknlove** [snd/url-pattern#50]
// https://repl.it/repls/DimpledExpensiveModule

const UrlPattern = require('url-pattern')
const pattern = new UrlPattern('/foo/:bar')

console.log(pattern.match('/foo/something')) // Match

console.log(pattern.match('/foo/some.thing')) // Does not match

**Comment by snd** [comment]
hey @hacknlove,

i hope reading my answer to this similar issue will help you https://github.com/snd/url-pattern/issues/26

**Comment by snd** [comment]
this is working as expected. please read my answer in #26. closing
