### ISSUE TITLE
Support for embedded urls as query parameters possible?

### ISSUE THREAD

**Issue by seantcanavan** [snd/url-pattern#52]
Hey,

First of all love the library. Got 90% of the way through my implementation of a URL matching algorithm with `url-pattern` as the backbone but hit a snag on an edge-case unfortunately. 

Is there any way to cleanly support urls that have urls as query parameters? 

Example: `https://translate.google.com/translate?sl=auto&tl=es&u=yahoo.com`

It seems to cause a hiccup in the code.

`const pattern = new urlPattern('https://translate.google.com/translate?sl=auto&tl=es&u=yahoo.com');`

->

```
Error: could only partially parse pattern
    at new UrlPattern (/home/runner/node_modules/url-pattern/lib/url-pattern.js:391:13)
    at evalmachine.<anonymous>:50:17
    at Script.runInContext (vm.js:107:20)
    at Object.runInContext (vm.js:285:6)
    at evaluate (/run_dir/repl.js:133:14)
    at ReadStream.<anonymous> (/run_dir/repl.js:116:5)
    at ReadStream.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at ReadStream.Readable.push (_stream_readable.js:220:10)   
```

Any ideas?

**Comment by snd** [comment]
Hey Sean,

i'm glad you like the library.

parsing fails in your example because the pattern string in:

```javascript
const pattern = new UrlPattern("https://translate.google.com/translate?sl=auto&tl=es&u=yahoo.com");
```

contains a `:` at index 5.
in url-pattern's default syntax (which you can change, [explained here](https://github.com/snd/url-pattern#customize-the-pattern-syntax)) the character `:` starts a named segment.
url-pattern expects a segment name to follow `:`.
per default `/` is not valid in a segment name (again, you can change that) - so parsing fails.

you can escape the `:` with the default escape sequence `\\` to make your pattern parse:

```javascript
const pattern = new UrlPattern("https\\://translate.google.com/translate?sl=auto&tl=es&u=yahoo.com");
```

that pattern is not very useful in my opinion as you could achieve the same with a simple string comparison.

maybe you could explain what you're trying to achieve?

**Comment by snd** [comment]
if the query parameters are in fixed positions you can use url-pattern to parse them:

```javascript
> const pattern = new UrlPattern("https\\://translate.google.com/translate?sl=auto&tl=:targetLanguage&u=:url", {
  segmentValueCharset: "a-zA-Z0-9-_~ %.",
});
> pattern.match("https://translate.google.com/translate?sl=auto&tl=es&u=yahoo.com");
{
  targetLanguage: "es",
  url: "yahoo.com",
}
```

the cleaner approach is to split the url at `?`, parse the first part with url pattern and the query part with a good query parser library like https://github.com/hapijs/qs.

please also read https://github.com/snd/url-pattern#how-do-i-match-the-query-part-of-an-url-

**Comment by seantcanavan** [comment]
Amazing thank you! I'm working on a legacy URL pattern matching system that isn't necessarily designed to pull out path parameters like yours does (and quite cleverly as well I should add) but is strictly doing pattern matching on urls with wildcard characters like `*`.

For instance: `new UrlPattern("https://images.google.com/*")` and then using that to match against incoming URLs like `images.google.com/image?id=498232`. I will be cognizant going forward of `url-pattern`'s reserved characters and matching behavior. Especially in relation to protocols and special symbols.

I think this has fixed my issue but I'm going to continue testing for the interim.

**Comment by seantcanavan** [comment]
@snd so far so good with my extended testing. for your curiosity your library does a great job of implementing a good portion of Google Chrome's `match patterns` API which is awesome. If you're curious the link is here: https://developers.chrome.com/extensions/match_patterns

And that's exactly what I'm using the library for. Hope that helps!
