### ISSUE TITLE
Couldn't match this pattern "/v:major.:minor/*"

### ISSUE THREAD

**Issue by abdelhady** [snd/url-pattern#6]
I'm trying to match the api version number from the url like this:

```coffeescript
UrlPattern = require 'url-pattern'
pattern = UrlPattern.newPattern '/v:major.:minor/*'
result = pattern.match(req.path)
console.log result
```
When I use this url `/v1.1/resource/?token=1234567890` it gives me:
```javascript
{ 'major.:minor': '1.1', _: [ 'resource/' ] }
```

but I'm trying to match the `:major` & `:minor` version numbers!

**Comment by snd** [comment]
sorry for taking so long to answer !

`:major.minor` matches everything until the next `/` (or custom separator).
this is intentional.

the best solution at the moment is something like this:

``` coffeescript
UrlPattern = require 'url-pattern'
pattern = UrlPattern.newPattern '/v:version/*'
result = pattern.match(req.path)
if result?
  [minor, major] = result.version.split('.')
```

it would certainly be useful to allow multiple characters to act as separators
which would make your example behave as you wanted it to.

i will improve the way separators are handled in the next version.

i am leaving this issue open to remind me of that.

**Comment by abdelhady** [comment]
I thought the semicolon in `:major` & in `:minor` are enough to do the trick (like one could do when adding a route to Express framework), but anyway I did something similar to the solution you proposed,

I'm glad you are going to consider it in next release, & I think if you concentrated on matching with the semicolon somehow, it would be much more accurate.

Good Luck :)

**Comment by snd** [comment]
yes, that would be ideal and thats how it should work.

`:` followed by at least one alphanumeric char (name) should match everything until the next non-alphanumeric char.

**Comment by abdelhady** [comment]
But this didn't match `v:major.:minor` with me although I'm using semicolons before `major` & before `minor`

**Comment by snd** [comment]
true.

my last comment was not about the current behaviour.
it was about ideal behaviour that i will implement in the next version.
sorry if i was being unclear :)

**Comment by abdelhady** [comment]
Never mind :) , it is great to hear that :+1:

**Comment by snd** [comment]
in version 0.8 this is now working as you expected :)

see all changes here: https://github.com/snd/url-pattern#08

**Comment by abdelhady** [comment]
Great :)
I'll apply it in my project soon, thanks for the follow up, I hope you the best in your projects.
